### ISSUE TITLE
vscode folder

### ISSUE THREAD

**Issue by michaelsauter** [opitzconsulting/generator-node-express-typescript#7]
https://github.com/opitzconsulting/generator-node-express-typescript/tree/master/generators/app/templates/_vscode

Shouldn't this be gitignored?

**Comment by rattermeyer** [comment]
No. It was added, beacuse the upstream project integrated vscode support. See [README](https://github.com/opitzconsulting/generator-node-express-typescript#highlights-of-the-latest-release)
